import {
  MdHome,
  MdCode,
  MdMusicNote,
  MdSchool,
  MdGraphicEq,
  MdOndemandVideo,
  MdSportsEsports,
  MdLiveTv,
  MdFitnessCenter,
  MdCheckroom,
  MdFaceRetouchingNatural,
  MdTheaterComedy,
  MdDeveloperMode,
} from "react-icons/md";

export const categories = [
  { name: "New", icon: <MdHome /> },
  { name: "Coding", icon: <MdCode /> },
  { name: "ReactJS", icon: <MdCode /> },
  { name: "NextJS", icon: <MdCode /> },
  { name: "Music", icon: <MdMusicNote /> },
  { name: "Education", icon: <MdSchool /> },
  { name: "Podcast", icon: <MdGraphicEq /> },
  { name: "Movie", icon: <MdOndemandVideo /> },
  { name: "Gaming", icon: <MdSportsEsports /> },
  { name: "Live", icon: <MdLiveTv /> },
  { name: "Sport", icon: <MdFitnessCenter /> },
  { name: "Fashion", icon: <MdCheckroom /> },
  { name: "Beauty", icon: <MdFaceRetouchingNatural /> },
  { name: "Comedy", icon: <MdTheaterComedy /> },
  { name: "Gym", icon: <MdFitnessCenter /> },
  { name: "Crypto", icon: <MdDeveloperMode /> },
];
